### ISSUE TITLE
Type error: can't concat str to bytes

### ISSUE THREAD

**Issue by daniellezhang** [bcgsc/Trans-NanoSim#4]
Hi, I was running read-analysis.py and received this following error message after Minimap2 has run:
`M::main] CMD: minimap2 --cs -ax map-ont ../../data/ref/gencode.v29.transcripts.fa training.fasta
[M::main] Real time: 1062.136 sec; CPU: 3207.338 sec
2019-01-15 16:39:58: Reads length distribution analysis
Traceback (most recent call last):
  File "../src/read_analysis.py", line 302, in <module>
    main()
  File "../src/read_analysis.py", line 266, in main
    count_aligned = align.head_align_tail(outfile, num_bins, t_alnm_ext, dict_ref_len)
  File "/wehisan/bioinf/elvis/bioinf/dzhang/Trans-NanoSim/src/head_align_tail_dist.py", line 126, in head_align_tail
    out6.write(head_seq + "\n")
TypeError: can't concat str to bytes
`

**Comment by saberhq** [comment]
Dear @daniellezhang . Thanks for reporting this. First, I should say that in my explanation below (and in the code) head sequence is the unaligned part soft-clipped from the beginning of the read.

Line 126 of the "head_align_tail_dist.py" simply writes the head sequence extracted using HTSeq module. I suspect that there is something wrong with the alignment SAM file you used. Maybe it is not complete and somethings missing. 

Is it possible for you to send me the SAM alignment file you are using? If it is not possible, my best help would be to run the minimap2 separately and then feed in the alignment file (SAM format) to Trans-NanoSim and see if it works.

To sum it up, the error you mentioned means that the type of the head sequence is not **str** but **bytes** and it is simply not possible. The way I extract the head sequence is that I use HTSeq module. You can use similar code to the one I provide here to double check your SAM file.

```
import HTSeq
sam_reader = HTSeq.SAM_Reader
my_alignments = sam_reader("/location/to/your/alignment/file/xx.sam")
for alnm in my_alignments:
    head_info = alnm.cigar[0]
    tail_info = alnm.cigar[-1]
    if head_info.type == "S" or head_info.type == "H":
        head = head_info.size
    else:
        head = 0
    head_sequence = alnm.read.seq[:head]
```

@CharlesTaylor you may also benefit from this. I don't know whether you experienced the same problem or not. But you were interested in this issue and that's why I mentioned you here.

**Comment by saberhq** [comment]
Dear @daniellezhang 

I was actually working on incorporating this pipeline within the [NanoSim](https://github.com/bcgsc/NanoSim) repo. The work is done and you may now use it to simulate both genomic and transcriptomic reads! This repo is now deprecated.

Let me know if you have any questions.
